# Generated by Django 3.0.5 on 2020-04-13 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('shortened_url', models.CharField(db_index=True, default='', max_length=10, unique=True)),
                ('visits', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_access_date', models.DateTimeField(null=True)),
                ('reset_date', models.DateTimeField(null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('disabled_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
